apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-service
  namespace: default
  labels:
    app: nginx-service
spec:
  ports:
    - name: port
      port: 8082
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-deployment
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
